name: crc
description: CRC calculator written in Dart supporting 50+ different CRC8, CRC16, CRC32 and CRC64 formulas.
version: 0.0.2
homepage: https://pwa.ir
repository: https://github.com/xclud/dart_crc/

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.21.3
  lints: ^2.0.0
