name: crc
description: CRC calculator writtent in pure Dart. Supports CRC16, Xmodem and CCITT.
version: 0.0.1
homepage: https://pwa.ir
repository: https://github.com/xclud/dart_crc/

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.20.0
  lints: ^1.0.1
